name: example-app CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [closed]
    branches: [ "master" ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - 
        name: Debug Environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Docker directory contents (if exists):"
          ls -la docker || echo "Docker directory not found"
          echo "Finding all Dockerfiles:"
          find . -name "Dockerfile" -type f
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ secrets.GHCR_USERNAME }}
            password: ${{ secrets.GHCR_TOKEN }}
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
            context: .
            file: ./docker/Dockerfile
            push: true
            tags: ghcr.io/oudrius/example-app:latest
